-d C:\Users\Xie\Desktop\verilog\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\Xie\Desktop\verilog\fpga_project\src\yingjiao.cst
-cfg C:\Users\Xie\Desktop\verilog\fpga_project\impl\pnr\device.cfg
-sdc C:\Users\Xie\Desktop\verilog\fpga_project\src\fpga_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
